name: Generuj HTML soubory

on:
  workflow_dispatch:       # manuální spuštění
  schedule:
    - cron: '0 6 * * *'     # každý den v 6:00
    - cron: '0 20 * * *'    # každý den ve 20:00

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas beautifulsoup4 lxml requests

      - name: Run script
        run: python terminova_listina_facr.py

      - name: Commit & push výsledky
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add *.html
          git commit -m "Automatická aktualizace HTML" || echo "Žádné změny ke commitu"

          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/MustafaHadzi/terminova_listina_facr.git
          git push origin main
