name: Generuj HTML soubory

on:
  workflow_dispatch:       # manuální spuštění
  schedule:
    - cron: '0 6 * * *'     # každý den v 6:00
    - cron: '0 20 * * *'    # každý den ve 20:00

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas beautifulsoup4 lxml

      - name: Run script
        run: python terminova_listina_facr.py

      - name: Commit HTML files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Utkani_*.html
          git commit -m "Automatická aktualizace HTML zápasů" || echo "Nic se nezměnilo"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
